# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-19 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
    ]
