# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-22 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='last modified')),
                ('last_four', models.CharField(max_length=4)),
                ('brand_card', models.CharField(choices=[(b'VISA', b'VISA'), (b'MASTERCARD', b'MASTERCARD'), (b'AMEX', b'AMEX')], max_length=10)),
                ('conekta_card', models.CharField(max_length=254)),
                ('is_default', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
