# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-18 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
