# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-25 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='brand_card',
            field=models.CharField(choices=[(b'VISA', b'VISA'), (b'MC', b'MASTERCARD'), (b'AMERICAN_EXPRESS', b'AMERICAN EXPRESS')], max_length=100),
        ),
    ]
