# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-22 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='last modified')),
                ('conekta_id', models.BinaryField()),
                ('card_last_four', models.CharField(max_length=4)),
                ('card_brand', models.CharField(choices=[(b'VISA', b'VISA'), (b'MASTERCARD', b'MASTERCARD'), (b'AMEX', b'AMEX')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('reference_id_conekta', models.BinaryField()),
                ('currency', models.CharField(max_length=10)),
                ('title_subscription', models.CharField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
