# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-26 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_fail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_brand',
            field=models.CharField(choices=[(b'VISA', b'VISA'), (b'MC', b'MASTERCARD'), (b'AMERICAN_EXPRESS', b'AMERICAN EXPRESS')], max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='conekta_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_id_conekta',
            field=models.CharField(max_length=255),
        ),
    ]
