# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-29 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_subscription_title'),
        ('payments', '0005_auto_20170528_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='users.Subscription'),
        ),
    ]
