# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-26 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='title',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
