# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-22 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_appointment',
            field=models.DateTimeField(),
        ),
    ]
