# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-24 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20170522_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time_zone',
            field=models.IntegerField(default=0),
        ),
    ]
