# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-24 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_zone',
            field=models.CharField(default=b'', max_length=254),
        ),
    ]
