# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-24 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_zone',
            field=models.CharField(default=b'', max_length=254),
        ),
    ]
