# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-26 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170525_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='next_pay_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
