# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-29 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_subscription_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='automatic_payment',
            field=models.BooleanField(default=True),
        ),
    ]
